apiVersion: apps/v1
kind: Deployment
metadata:
  name: hl7tool-deployment
  labels:
    app: hl7tool
spec:
  selector:
    matchLabels:
      app: hl7tool
  template:
    metadata:
      labels:
        app: hl7tool
    spec:
      containers:
      - name: hl7tool-container
        image: localhost/hl7-tool:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 6
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hl7tool-service
spec:
  type: NodePort
  selector:
    app: hl7tool
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tools-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/app-root: /default
spec:
  rules:
    - host: minikube-dev.local
      http:
        paths:
          - path: /default
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
          - path: /hl7-tool(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hl7tool-service
                port:
                  number: 8080
