apiVersion: apps/v1
kind: Deployment
metadata:
  name: hl7tool-deployment
  labels:
    app: hl7tool
spec:
  selector:
    matchLabels:
      app: hl7tool
  template:
    metadata:
      labels:
        app: hl7tool
    spec:
      containers:
      - name: hl7tool-container
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 6
          periodSeconds: 4
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hl7tool-service
spec:
  type: ClusterIP
  selector:
    app: hl7tool
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
